apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: inventory-image-internal
  spec:
    params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/full-bc/inventory
    type: image
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: inventory-image-external
  spec:
    params:
    - name: url
      value: quay.io/kitty_catt/inventory
    type: image    
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: inventory-source
  spec:
    params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/kitty-catt/inventory-ms-spring
    type: git
kind: List
